# ========== RefontCrafts ==========
# Создатель: https://t.me/orythix
# Настройки, база данных, и примеры рецептов (могут быть импортированы в БД при первом запуске).

settings:
  # префикс в сообщениях (можно цветами Minecraft)
  prefix: "§x§2§5§A§F§F§1R§x§2§2§A§8§F§2e§x§1§E§A§1§F§4f§x§1§B§9§B§F§5o§x§1§8§9§4§F§6n§x§1§4§8§D§F§7t§x§1§1§8§6§F§9C§x§0§D§7§F§F§Ar§x§0§A§7§8§F§Ba§x§0§7§7§2§F§Cf§x§0§3§6§B§F§Et§x§0§0§6§4§F§Fs &8»&7 "
  titles:
    # заголовок GUI рецептов верстака
    recipe: "§x§2§5§A§F§F§1С§x§2§3§A§A§F§2о§x§2§0§A§5§F§3з§x§1§E§A§0§F§4д§x§1§B§9§B§F§5а§x§1§9§9§6§F§6н§x§1§6§9§1§F§7и§x§1§4§8§C§F§8е §x§0§F§8§2§F§9р§x§0§C§7§D§F§Aе§x§0§A§7§8§F§Bц§x§0§7§7§3§F§Cе§x§0§5§6§E§F§Dп§x§0§2§6§9§F§Eт§x§0§0§6§4§F§Fа"
    # заголовок GUI рецептов наковальни
    anvil: "§x§2§5§A§F§F§1Р§x§2§3§A§B§F§2е§x§2§1§A§7§F§3ц§x§1§F§A§3§F§3е§x§1§D§9§E§F§4п§x§1§B§9§A§F§5т §x§1§7§9§2§F§6в §x§1§3§8§A§F§8н§x§1§0§8§5§F§9а§x§0§E§8§1§F§Aк§x§0§C§7§D§F§Aо§x§0§A§7§9§F§Bв§x§0§8§7§5§F§Cа§x§0§6§7§1§F§Dл§x§0§4§6§C§F§Dь§x§0§2§6§8§F§Eн§x§0§0§6§4§F§Fю"
  # Сопоставлять предметы по метаданным (true) или только по типу (false - имя/лоры игнорируются)
  exact_meta_match: false
  # возврат вещей при закрытии GUI без сохранения
  take_back_on_close: true
  # Значение XP по умолчанию для новой записи рецепта наковальни
  default_anvil_cost: 0

database:
  # тип БД: sqlite — локальный файл .db; mysql — удалённый сервер MySQL/MariaDB
  type: sqlite

  sqlite:
    # имя файла базы данных в папке плагина
    file: data.db

  mysql:
    # Хост MySQL
    host: 127.0.0.1
    # Порт MySQL
    port: 3306
    # Имя базы
    database: refontcrafts
    # Имя пользователя
    user: root
    # Пароль в одинарных кавычках — можно любые символы
    password: ''
    # Использовать SSL при подключении
    use_ssl: false
    # Доп. параметры строки подключения (опционально)
    params: 'useUnicode=true&characterEncoding=utf8'

  # Если БД пуста — импортировать примеры из секции recipes
  bootstrap_from_config: true
  # Асинхронное сохранение новых рецептов
  async_save: true
  # Авто‑миграция: при смене database.type рецепты переносятся из предыдущей БД в новую (если новая пуста).
  # Настройка не требуется — включено всегда.

messages:
  only_player: "&cТолько игрок."
  no_permission: "&cНедостаточно прав."
  recipe_fill_both: "&cЗаполни ингредиенты и результат."
  anvil_fill_both: "&cЗаполни оба входа и результат."
  saved_recipe: "&aРецепт сохранён: &f%id%"
  saved_anvil: "&aСохранён рецепт наковальни: &f%id% &7(стоимость: &f%cost%&7)"
  not_enough_levels: "&cНедостаточно уровней: нужно &f%cost%"
  no_inventory_space: "&cНет места в инвентаре."
  reloaded: "&aКонфиг и рецепты перезагружены."